name: Run tests

on:
    workflow_dispatch:
    push:
        paths-ignore:
            - "**.md"
        branches:
            - main
    pull_request:
        paths-ignore:
            - "**.md"

jobs:
    test:
        runs-on: ${{ matrix.os }}
        timeout-minutes: 20

        strategy:
            fail-fast: false
            matrix:
                julia-version: ["1.10", "1"]
                os: [ubuntu-latest, windows-latest, macOS-latest]

        outputs:
            output_dir: ${{ steps.set_output_dir.outputs.output_dir }}

        steps:
            - uses: actions/checkout@v4

            - name: Set output directory
              id: set_output_dir
              shell: bash
              run: |
                  mkdir -p $HOME/output
                  echo "output_dir=$HOME/output" >> "$GITHUB_OUTPUT"

            - uses: julia-actions/setup-julia@v2
              with:
                  version: ${{ matrix.julia-version }}

            - uses: julia-actions/julia-buildpkg@v1
            
            - uses: julia-actions/julia-runtest@v1
              env:
                  TEST_OUTPUT_DIR: ${{ steps.set_output_dir.outputs.output_dir }}

            - uses: actions/upload-artifact@v4
              if: failure()
              with:
                  name: hanoi_${{ matrix.os }}_${{ matrix.julia_version }}.pdf
                  path: ${{ steps.set_output_dir.outputs.output_dir }}/hanoi.pdf
