name: Run tests

on:
    workflow_dispatch:
    push:
        paths-ignore:
            - "**.md"
        branches:
            - main
    pull_request:
        paths-ignore:
            - "**.md"

jobs:
    test:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                julia-version: ["1.7"]
                os: [ubuntu-latest, windows-latest, macOS-latest]

        steps:
            - uses: actions/checkout@v2

            - name:
              if: ${{ matrix.os == 'windows-latest' }}
              run: |
                  mkdir -p $HOME/output
                  echo "output_dir=$(echo $HOME/output)" >> $env:GITHUB_ENV

            - name:
              if: ${{ matrix.os != 'windows-latest' }}
              run: |
                  mkdir -p $HOME/output
                  echo "output_dir=$(echo $HOME/output)" >> $GITHUB_ENV

            - uses: julia-actions/setup-julia@v1
              with:
                  version: ${{ matrix.julia-version }}
            - uses: julia-actions/julia-buildpkg@v1
            - uses: julia-actions/julia-runtest@v1
              env:
                  TEST_OUTPUT_DIR: ${{ env.output_dir }}

            - uses: actions/upload-artifact@v2
              with:
                  name: hanoi_${{ matrix.os }}_${{ matrix.julia_version }}.pdf
                  path: ${{ env.output_dir }}/hanoi.pdf
