name: Run tests

on:
    workflow_dispatch:
    push:
        paths-ignore:
            - "**.md"
        branches:
            - main
    pull_request:
        paths-ignore:
            - "**.md"

jobs:
    test:
        runs-on: ${{ matrix.os }}
        timeout-minutes: 30

        strategy:
            fail-fast: false
            matrix:
                julia-version: ["1.10", "1"]
                os: [ubuntu-latest, windows-latest, macOS-latest]

        steps:
            - uses: actions/checkout@v4

            - name:
              if: ${{ matrix.os == 'windows-latest' }}
              run: |
                  mkdir -p $HOME/output
                  echo "output_dir=$(echo $HOME/output)" >> $env:GITHUB_ENV

            - name:
              if: ${{ matrix.os != 'windows-latest' }}
              run: |
                  mkdir -p $HOME/output
                  echo "output_dir=$(echo $HOME/output)" >> $GITHUB_ENV

            - uses: julia-actions/setup-julia@v2
              with:
                  version: ${{ matrix.julia-version }}
                  
            - uses: julia-actions/julia-buildpkg@v1
            - uses: julia-actions/julia-runtest@v1
              env:
                  TEST_OUTPUT_DIR: ${{ env.output_dir }}
                  PUPPETEER_DOWNLOAD_BASE_URL: "https://storage.googleapis.com/chrome-for-testing-public"

            - uses: actions/upload-artifact@v4
              if: failure()
              with:
                  name: hanoi_${{ matrix.os }}_${{ matrix.julia_version }}.pdf
                  path: ${{ env.output_dir }}/hanoi.pdf
